---
# Clean K3s server installation
- name: Create k3s config directory
  file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0755'

- name: Generate k3s config
  template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    mode: '0644'

- name: Install k3s server
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -s - server --config /etc/rancher/k3s/config.yaml
  args:
    creates: /usr/local/bin/k3s

- name: Enable and start k3s service
  systemd:
    name: k3s
    enabled: yes
    state: started
    daemon_reload: yes

- name: Wait for k3s to be ready
  wait_for:
    port: 6443
    host: "{{ ansible_host }}"
    delay: 10
    timeout: 300