---
# PostgreSQL version
postgresql_version: "17"

# PostgreSQL configuration
postgresql_listen_addresses: "localhost"
postgresql_port: 5432
postgresql_max_connections: 200
postgresql_shared_buffers: "256MB"
postgresql_effective_cache_size: "1GB"
postgresql_work_mem: "4MB"
postgresql_maintenance_work_mem: "64MB"

# Databases to create
postgresql_databases:
  - name: bamboo
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8

# Users to create
postgresql_users:
  - name: bamboo
    password: "{{ vault_postgresql_bamboo_password }}"
    db: bamboo
    priv: ALL

# Backup configuration
postgresql_backup_enabled: true
postgresql_backup_dir: "/var/backups/postgresql"
postgresql_backup_retention_days: 7
postgresql_backup_s3_enabled: false
postgresql_backup_s3_bucket: ""
postgresql_backup_s3_region: "us-east-1"

# Security
postgresql_ssl_enabled: false
postgresql_password_encryption: scram-sha-256
